url: rombo-ai.github.io
title: "Rombo.ai" # the name of your site, e.g. ACME Corp.

# Engage Section
engage_main_title: "DISCOVER WHAT AI-DRIVEN SPECTRAL ANALYSIS CAN DO FOR YOU"
engage_sub_title: "Engage with Rombo AI"
engage_message_part_one: "Ready to transform your analytical processes? Connect with our experts to explore tailored solutions for
your business challenges. Reach out to our sales team, schedule a demo, or sign up for our newsletter for the latest insights and updates."


# Build settings
permalink: :title/
sass:
  sass_dir: _sass
  style:    compressed